services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: moodmix-backend:dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
