# Generated by Django 5.2.5 on 2025-08-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('firebase_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('spotify_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('spotify_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('spotify_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spotify_access_token', models.TextField(blank=True, null=True)),
                ('spotify_refresh_token', models.TextField(blank=True, null=True)),
                ('spotify_scope', models.TextField(blank=True, null=True)),
                ('spotify_token_type', models.CharField(default='Bearer', max_length=32)),
                ('spotify_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_states', to='MoodMixDjangoApp.userprofile')),
            ],
        ),
    ]
