# Generated by Django 5.2.5 on 2025-08-18 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMixDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(editable=False, max_length=140)),
                ('mood', models.CharField(max_length=64)),
                ('length', models.PositiveSmallIntegerField(default=10, help_text='Number of tracks (4–10). Defaults to 10.', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spotifyauthstate',
            index=models.Index(fields=['expires_at'], name='MoodMixDjan_expires_d2cd03_idx'),
        ),
        migrations.AddIndex(
            model_name='spotifyauthstate',
            index=models.Index(fields=['used_at'], name='MoodMixDjan_used_at_18ac65_idx'),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='MoodMixDjangoApp.userprofile'),
        ),
        migrations.AddIndex(
            model_name='playlistprofile',
            index=models.Index(fields=['owner', 'created_at'], name='MoodMixDjan_owner_i_ab4b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistprofile',
            index=models.Index(fields=['owner', 'name_key'], name='MoodMixDjan_owner_i_3a683c_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('mood__regex', '^\\s*$'), _negated=True), name='playlist_mood_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='playlistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='playlist_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='playlistprofile',
            constraint=models.UniqueConstraint(fields=('owner', 'name_key'), name='uniq_playlist_name_key_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='playlistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('length__gte', 4), ('length__lte', 10)), name='playlist_length_between_4_10'),
        ),
    ]
