# Generated by Django 5.2.5 on 2025-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMixDjangoApp', '0002_playlistprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistprofile',
            name='spotify_playlist_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
