# Generated by Django 5.2.5 on 2025-08-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMixDjangoApp', '0003_playlistprofile_spotify_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistprofile',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_playlist_create_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
