# Generated by Django 5.2.5 on 2025-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMixDjangoApp', '0004_playlistprofile_spotify_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistprofile',
            name='cached_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='cached_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='cached_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='cached_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='playlistprofile',
            name='snapshot_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
