# Generated by Django 5.2.5 on 2025-09-15 09:15

import MoodMixDjangoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMixDjangoApp', '0005_playlistprofile_cached_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_then_build_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_then_build_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlistprofile',
            name='id',
            field=models.CharField(default=MoodMixDjangoApp.models.gen_alphanum_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spotifyauthstate',
            name='id',
            field=models.CharField(default=MoodMixDjangoApp.models.gen_alphanum_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=MoodMixDjangoApp.models.gen_alphanum_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
