name: CI
on:
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Django smoke check
        run: python manage.py check
      - name: Placeholder tests
        run: |
          echo "def test_true(): assert True" > tests_smoke.py
          python -m pip install pytest
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image (python 3.13.3)
        run: docker build -t backend:ci-${{ github.sha }} ./backend
